// src/types/cabinet.ts

// ─── 基礎型別 ─────────────────────────────────────────────────────────────────

export interface AreaMeasure {
  cm2: number;
  m2: number;
  cai: number;
}

export interface MaterialRef {
  materialId: string;
  materialName: string;
  unit: string;
  pricePerUnit: number;
  minCai: number | null;
}

// ─── 輸入型別 ─────────────────────────────────────────────────────────────────

export type DoorType = "HINGED" | "SLIDING";
export type ProfileHandleStyle = "none" | "SFJA" | "SFJB" | "SFJC" | "SFJD" | "SFCA";
export type LightGrooveSide = "none" | "left" | "right";
export type LightGrooveFace = "none" | "top" | "bottom";

export interface LightGrooveSwitch {
  enabled: boolean;
  offsetFromFrontMm: number;
}

export interface UnitLightGrooves {
  topInner: LightGrooveSwitch;
  sideInner: LightGrooveSwitch;
}

export interface MiddleDividerLightGroove {
  side: LightGrooveSide;
  offsetFromFrontMm: number;
}

export interface ShelfLightGroove {
  side: LightGrooveFace;
  offsetFromFrontMm: number;
}

export interface UnitAddons {
  frontEdgeABS: "none" | "one_long" | "two_long";
  lightGrooves?: UnitLightGrooves;
}

export interface MiddleDividerAddons {
  doubleDrillHoles: boolean;
  nonStandardHoles: boolean;
  lightGroove?: MiddleDividerLightGroove;
}

export interface DoorAddons {
  patternMatch: "none" | "grain";
  temperedGlass: boolean;
  hingeHoleDrilling: boolean;
  wireMeshPaint: boolean;
  profileHandle: {
    style: ProfileHandleStyle;
    lengthCm: number;
    lengthModification: boolean;
  };
}

export const DEFAULT_UNIT_ADDONS: UnitAddons = {
  frontEdgeABS: "none",
  lightGrooves: {
    topInner: { enabled: false, offsetFromFrontMm: 50 },
    sideInner: { enabled: false, offsetFromFrontMm: 50 },
  },
};

export const DEFAULT_MIDDLE_DIVIDER_ADDONS: MiddleDividerAddons = {
  doubleDrillHoles: false,
  nonStandardHoles: false,
  lightGroove: { side: "none", offsetFromFrontMm: 50 },
};

export const DEFAULT_DOOR_ADDONS: DoorAddons = {
  patternMatch: "none",
  temperedGlass: false,
  hingeHoleDrilling: false,
  wireMeshPaint: false,
  profileHandle: {
    style: "none",
    lengthCm: 40,
    lengthModification: false,
  },
};

export interface DoorInput {
  id: string;
  type: DoorType;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  materialRef: MaterialRef | null;
  addons: DoorAddons;
  hingeMaterialRef?: MaterialRef | null;
  railMaterialRef?: MaterialRef | null;
  wireMeshMaterialRef?: MaterialRef | null;
  useAluminumHandle?: boolean;
  aluminumHandleMaterialRef?: MaterialRef | null;
}

export interface HardwareItemInput {
  id: string;
  name: string;
  quantity: number;
  materialRef: MaterialRef | null;
}

export interface MiddleDividerInput {
  id: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  materialRef: MaterialRef | null;
  addons: MiddleDividerAddons;
}

export interface ShelfInput {
  id: string;
  widthCm: number;
  depthCm: number;
  quantity: number;
  materialRef: MaterialRef | null;
  lightGroove?: ShelfLightGroove;
}

export interface KickPlateInput {
  widthCm: number;
  heightCm: number;
  materialRef: MaterialRef | null;
}

export interface DrawerInput {
  id: string;
  name: string;
  widthCm: number;
  heightCm: number;
  depthCm: number;
  railLengthCm: number;
  grooveSpec: "12" | "8.5" | "9";
  quantity: number;
  railMaterialRef: MaterialRef | null;
  wallMaterialRef: MaterialRef | null;
  bottomMaterialRef: MaterialRef | null;
}

export interface CabinetUnitInput {
  id: string;
  name: string;
  widthCm: number;
  depthCm: number;
  heightCm: number;
  quantity: number;
  hasBackPanel: boolean;
  panelMaterialRef: MaterialRef | null;
  backPanelMaterialRef: MaterialRef | null;
  addons: UnitAddons;
  middleDividers: MiddleDividerInput[];
  shelves: ShelfInput[];
  drawers: DrawerInput[];
  doors: DoorInput[];
  hardwareItems: HardwareItemInput[];
  kickPlate: KickPlateInput | null;
}

// ─── 輸出型別 ─────────────────────────────────────────────────────────────────

export interface PanelResult {
  id: string;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  singleArea: AreaMeasure;
  totalArea: AreaMeasure;
  billableTotalArea: AreaMeasure;
  materialRef: MaterialRef | null;
  unitCost: number;
  subtotal: number;
  addonsCost: number;
  lightGrooveCost: number;
  processes: PanelProcessResult[];
  isAutoGenerated: boolean;
  note?: string;
}

export interface PanelProcessResult {
  id: string;
  label: string;
  quantity: number;
  unitCost: number;
  cost: number;
  includedInSubtotal: boolean;
}

export interface DoorResult {
  id: string;
  type: DoorType;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  singleArea: AreaMeasure;
  totalArea: AreaMeasure;
  billableTotalArea: AreaMeasure;
  materialRef: MaterialRef | null;
  subtotal: number;
  addonsCost: number;
}

export interface HardwareResult {
  id: string;
  name: string;
  description: string;
  quantity: number;
  materialRef: MaterialRef | null;
  unitCost: number;
  subtotal: number;
}

export interface AccessoryResult {
  id: string;
  name: string;
  widthCm: number;
  heightCm: number;
  quantity: number;
  singleArea: AreaMeasure;
  totalArea: AreaMeasure;
  materialRef: MaterialRef | null;
  subtotal: number;
}

export interface CabinetUnitSummary {
  totalAreaCm2: number;
  totalAreaM2: number;
  totalAreaCai: number;
  panelsCost: number;
  internalPartsCost: number;
  doorsCost: number;
  hardwareCost: number;
  accessoriesCost: number;
  addonsCost: number;
  boardBodyCost: number;
  boardBackingCost: number;
  boardDoorCost: number;
  addonsBreakdown: AddonsBreakdown;
  totalCost: number;
}

export interface AddonsBreakdown {
  frontEdgeABS: number;
  doubleDrillHoles: number;
  nonStandardHoles: number;
  patternMatch: number;
  temperedGlass: number;
  hingeHoleDrilling: number;
  backPanelGroove: number;
  lightGroove: number;
}

export interface CabinetUnitResult {
  unitId: string;
  unitName: string;
  quantity: number;
  panels: PanelResult[];
  internalParts: PanelResult[];
  doors: DoorResult[];
  hardware: HardwareResult[];
  accessories: AccessoryResult[];
  summary: CabinetUnitSummary;
}

export interface CabinetProjectResult {
  unitResults: CabinetUnitResult[];
  projectTotal: number;
}
