"use client";

import { Fragment } from "react";
import type { CabinetUnitResult, DoorResult, HardwareResult, PanelResult } from "@/types";
import { formatCurrency, formatNumber } from "@/lib/utils";
import { AreaDisplay } from "@/components/shared/AreaDisplay";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

interface Props {
  result: CabinetUnitResult;
}

type BoardRow = PanelResult | DoorResult;

interface DisplayProcessRow {
  id: string;
  label: string;
  quantity: number;
  unitCost: number;
  cost: number;
}

const tableShellClass = "overflow-x-auto rounded-md border";
const headerCellClass = "px-3 py-2 text-xs font-medium text-muted-foreground";
const bodyCellClass = "px-3 py-2 align-top";
const numericCellClass = `${bodyCellClass} text-right tabular-nums whitespace-nowrap`;

function unitPrice(row: BoardRow): number {
  return "unitCost" in row ? row.unitCost : row.materialRef?.pricePerUnit ?? 0;
}

function isAutoGenerated(row: BoardRow): boolean {
  return "isAutoGenerated" in row && row.isAutoGenerated;
}

function panelProcessCost(row: BoardRow): number {
  return "processes" in row
    ? row.processes.reduce((acc, process) => acc + (process.includedInSubtotal ? process.cost : 0), 0)
    : 0;
}

function rowBaseSubtotal(row: BoardRow): number {
  return row.subtotal - panelProcessCost(row);
}

function processLabel(label: string): string {
  return `加工-${label.replace(": ", ":")}`;
}

function formatQuantity(quantity: number): string {
  return Number.isInteger(quantity) ? formatNumber(quantity, 0) : formatNumber(quantity, 2);
}

function isDrawerPanel(row: PanelResult): boolean {
  return row.name.startsWith("抽屜") || row.id.includes("drawer");
}

function isDrawerHardware(row: HardwareResult): boolean {
  return row.id.endsWith("-rail") || row.name.includes("抽屜");
}

function isProfileHandleProcess(row: HardwareResult): boolean {
  return row.id.includes("-profile-handle");
}

function isDoorHardware(row: HardwareResult): boolean {
  return (
    row.id.includes("-hinge") ||
    row.id.includes("-push-pull") ||
    row.id.includes("-wire-mesh") ||
    row.id.includes("-aluminum-handle") ||
    isProfileHandleProcess(row)
  );
}

function profileHandleProcessLabel(row: HardwareResult): string {
  if (row.id.includes("-profile-handle-modification")) {
    return "造型把手長度修改";
  }

  const style = row.name.match(/SFJ[ABCD]|SFCA/)?.[0];
  return style ? `造型把手加工 ${style}` : "造型把手加工";
}

function buildDoorProcessRows(hardwareRows: HardwareResult[]): Record<string, DisplayProcessRow[]> {
  return hardwareRows.filter(isProfileHandleProcess).reduce<Record<string, DisplayProcessRow[]>>((acc, row) => {
    const doorId = row.id.replace(/-profile-handle(?:-modification)?$/, "");
    acc[doorId] = [
      ...(acc[doorId] ?? []),
      {
        id: row.id,
        label: profileHandleProcessLabel(row),
        quantity: row.quantity,
        unitCost: row.unitCost,
        cost: row.subtotal,
      },
    ];
    return acc;
  }, {});
}

function BoardNameCell({ row }: { row: BoardRow }) {
  return (
    <div className="min-w-0 space-y-1">
      <div className="flex min-w-0 items-center gap-1.5">
        <span className="truncate font-medium">{row.name}</span>
        {isAutoGenerated(row) && (
          <Badge variant="outline" className="shrink-0 px-1 py-0 text-[10px]">
            自動
          </Badge>
        )}
        {"type" in row && (
          <Badge variant="secondary" className="shrink-0 px-1 py-0 text-[10px]">
            {row.type === "HINGED" ? "鉸鏈門" : "滑門"}
          </Badge>
        )}
      </div>
      <div className="truncate text-xs text-muted-foreground">
        {row.materialRef?.materialName ?? <span className="text-orange-600">未選材料</span>}
      </div>
    </div>
  );
}

function BoardTable({
  title,
  rows,
  processRowsByRowId = {},
}: {
  title: string;
  rows: BoardRow[];
  processRowsByRowId?: Record<string, DisplayProcessRow[]>;
}) {
  if (rows.length === 0) return null;

  return (
    <section className="space-y-2">
      <h4 className="text-sm font-semibold text-slate-700">{title}</h4>
      <div className={tableShellClass}>
        <table className="w-full min-w-[700px] table-fixed text-sm">
          <colgroup>
            <col className="w-[38%]" />
            <col className="w-[112px]" />
            <col className="w-[64px]" />
            <col className="w-[92px]" />
            <col className="w-[104px]" />
            <col className="w-[104px]" />
          </colgroup>
          <thead className="bg-muted/40">
            <tr className="border-b">
              <th className={`${headerCellClass} text-left`}>名稱 / 材料</th>
              <th className={`${headerCellClass} text-right`}>尺寸(cm)</th>
              <th className={`${headerCellClass} text-right`}>數量</th>
              <th className={`${headerCellClass} text-right`}>才數</th>
              <th className={`${headerCellClass} text-right`}>單價</th>
              <th className={`${headerCellClass} text-right`}>小計</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => {
              const panelProcesses = "processes" in row
                ? row.processes.map((process) => ({
                    id: process.id,
                    label: process.label,
                    quantity: process.quantity,
                    unitCost: process.unitCost,
                    cost: process.cost,
                  }))
                : [];
              const displayProcesses = [...panelProcesses, ...(processRowsByRowId[row.id] ?? [])];

              return (
                <Fragment key={row.id}>
                  <tr className="border-b border-muted/50 hover:bg-muted/20">
                    <td className={`${bodyCellClass} min-w-0`}>
                      <BoardNameCell row={row} />
                    </td>
                    <td className={numericCellClass}>{formatNumber(row.widthCm, 1)} x {formatNumber(row.heightCm, 1)}</td>
                    <td className={numericCellClass}>{row.quantity}</td>
                    <td className={numericCellClass}>
                      <AreaDisplay area={row.totalArea} />
                      {row.billableTotalArea.cai > row.totalArea.cai && (
                        <span className="block text-[11px] text-orange-600">
                          計價 <AreaDisplay area={row.billableTotalArea} />
                        </span>
                      )}
                    </td>
                    <td className={numericCellClass}>
                      {row.materialRef ? (
                        <>
                          {formatCurrency(unitPrice(row))}
                          <span className="text-muted-foreground">/{row.materialRef.unit}</span>
                        </>
                      ) : (
                        <span className="text-muted-foreground">-</span>
                      )}
                    </td>
                    <td className={`${numericCellClass} font-semibold`}>{formatCurrency(rowBaseSubtotal(row))}</td>
                  </tr>
                  {displayProcesses.map((process) => (
                    <tr key={process.id} className="border-b border-muted/50 bg-muted/10">
                      <td className={`${bodyCellClass} pl-7`}>
                        <div className="font-medium text-slate-700">{processLabel(process.label)}</div>
                        <div className="text-xs text-muted-foreground">後加工</div>
                      </td>
                      <td className={numericCellClass}>-</td>
                      <td className={numericCellClass}>{formatQuantity(process.quantity)}</td>
                      <td className={numericCellClass}>-</td>
                      <td className={numericCellClass}>{formatCurrency(process.unitCost)}</td>
                      <td className={`${numericCellClass} font-semibold`}>{formatCurrency(process.cost)}</td>
                    </tr>
                  ))}
                </Fragment>
              );
            })}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function HardwareTable({ title, rows }: { title: string; rows: HardwareResult[] }) {
  if (rows.length === 0) return null;

  return (
    <section className="space-y-2">
      <h4 className="text-sm font-semibold text-slate-700">{title}</h4>
      <div className={tableShellClass}>
        <table className="w-full min-w-[520px] table-fixed text-sm">
          <colgroup>
            <col className="w-[52%]" />
            <col className="w-[72px]" />
            <col className="w-[116px]" />
            <col className="w-[104px]" />
          </colgroup>
          <thead className="bg-muted/40">
            <tr className="border-b">
              <th className={`${headerCellClass} text-left`}>名稱 / 說明</th>
              <th className={`${headerCellClass} text-right`}>數量</th>
              <th className={`${headerCellClass} text-right`}>單價</th>
              <th className={`${headerCellClass} text-right`}>小計</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((hardware) => (
              <tr key={hardware.id} className="border-b border-muted/50 hover:bg-muted/20">
                <td className={`${bodyCellClass} min-w-0`}>
                  <div className="truncate font-medium">{hardware.name}</div>
                  <div className="truncate text-xs text-muted-foreground">
                    {hardware.description || hardware.materialRef?.materialName || "-"}
                  </div>
                </td>
                <td className={numericCellClass}>{hardware.quantity}</td>
                <td className={numericCellClass}>
                  {hardware.unitCost > 0 ? (
                    <>
                      {formatCurrency(hardware.unitCost)}
                      {hardware.materialRef && <span className="text-muted-foreground">/{hardware.materialRef.unit}</span>}
                    </>
                  ) : (
                    <span className="text-muted-foreground">-</span>
                  )}
                </td>
                <td className={`${numericCellClass} font-semibold`}>{formatCurrency(hardware.subtotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export function CabinetResultPanel({ result }: Props) {
  const { summary } = result;
  const drawerPanels = result.internalParts.filter(isDrawerPanel);
  const internalParts = result.internalParts.filter((row) => !isDrawerPanel(row));
  const drawerHardware = result.hardware.filter(isDrawerHardware);
  const doorProcessRowsByDoorId = buildDoorProcessRows(result.hardware);
  const doorHardware = result.hardware.filter((row) => isDoorHardware(row) && !isDrawerHardware(row) && !isProfileHandleProcess(row));
  const otherHardware = result.hardware.filter((row) => !isDrawerHardware(row) && !isDoorHardware(row));

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <Card className="bg-muted/30">
          <CardContent className="p-3">
            <p className="text-xs text-muted-foreground">總板材面積</p>
            <p className="text-lg font-bold">{formatNumber(summary.totalAreaCai, 2)} 才</p>
            <p className="text-xs text-muted-foreground">{formatNumber(summary.totalAreaM2, 3)} m2</p>
          </CardContent>
        </Card>
        <Card className="bg-primary/5">
          <CardContent className="p-3">
            <p className="text-xs text-muted-foreground">估算總價</p>
            <p className="text-lg font-bold text-primary">{formatCurrency(summary.totalCost)}</p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-5">
        <BoardTable title="桶身板材" rows={result.panels} />
        <BoardTable title="內部構件（中隔板 / 層板）" rows={internalParts} />

        {(drawerPanels.length > 0 || drawerHardware.length > 0) && (
          <div className="space-y-3">
            <BoardTable title="抽屜板材" rows={drawerPanels} />
            <HardwareTable title="抽屜五金" rows={drawerHardware} />
          </div>
        )}

        {(result.doors.length > 0 || doorHardware.length > 0) && (
          <div className="space-y-3">
            <BoardTable title="門片" rows={result.doors} processRowsByRowId={doorProcessRowsByDoorId} />
            <HardwareTable title="門片鉸鏈 / 加工" rows={doorHardware} />
          </div>
        )}

        <HardwareTable title="五金 / 另料" rows={otherHardware} />

        {result.accessories.length > 0 && (
          <section className="space-y-2">
            <h4 className="text-sm font-semibold text-slate-700">配件</h4>
            <div className={tableShellClass}>
              <table className="w-full min-w-[480px] table-fixed text-sm">
                <colgroup>
                  <col className="w-[44%]" />
                  <col className="w-[128px]" />
                  <col className="w-[72px]" />
                  <col className="w-[104px]" />
                </colgroup>
                <tbody>
                  {result.accessories.map((accessory) => (
                    <tr key={accessory.id} className="border-b border-muted/50 hover:bg-muted/20">
                      <td className={`${bodyCellClass} font-medium`}>{accessory.name}</td>
                      <td className={numericCellClass}>{accessory.widthCm} x {accessory.heightCm} cm</td>
                      <td className={numericCellClass}>{accessory.quantity}</td>
                      <td className={`${numericCellClass} font-semibold`}>{formatCurrency(accessory.subtotal)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        )}
      </div>

      <Separator />
      <div className="space-y-1 text-sm">
        <div className="flex justify-between text-muted-foreground">
          <span>桶身板材</span><span>{formatCurrency(summary.boardBodyCost)}</span>
        </div>
        {summary.boardBackingCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>背板</span><span>{formatCurrency(summary.boardBackingCost)}</span>
          </div>
        )}
        {summary.boardDoorCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>門片</span><span>{formatCurrency(summary.boardDoorCost)}</span>
          </div>
        )}
        {summary.hardwareCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>五金</span><span>{formatCurrency(summary.hardwareCost)}</span>
          </div>
        )}
        {summary.addonsCost > 0 && (
          <div className="flex justify-between text-muted-foreground">
            <span>加工費</span><span>{formatCurrency(summary.addonsCost)}</span>
          </div>
        )}
        <Separator />
        <div className="flex justify-between text-base font-bold">
          <span>總計</span>
          <span className="text-primary">{formatCurrency(summary.totalCost)}</span>
        </div>
      </div>
    </div>
  );
}
