import { ADDON_PRICES, UNIT_CONFIG } from "../config/units";
import { DEFAULT_DOOR_ADDONS } from "../../types";
import type {
  AccessoryResult,
  CabinetProjectResult,
  CabinetUnitInput,
  CabinetUnitResult,
  DoorInput,
  DoorResult,
  HardwareResult,
  MaterialRef,
  PanelProcessResult,
  PanelResult,
} from "../../types";

export type MaterialSummaryRowKind = "material" | "process" | "hardware" | "accessory";

export interface MaterialSummaryRow {
  id: string;
  category: string;
  materialId: string | null;
  material: string;
  itemName: string;
  quantity: number | null;
  size: string;
  cai: number | null;
  caiLabel: string;
  note: string;
  unitPrice: number | null;
  subtotal: number | null;
  kind: MaterialSummaryRowKind;
}

export interface MaterialCaiTotal {
  materialId: string;
  materialName: string;
  cai: number;
}

export interface CabinetUnitMaterialSummary {
  unitId: string;
  unitName: string;
  rows: MaterialSummaryRow[];
  materialCaiTotals: MaterialCaiTotal[];
  hardwareRows: MaterialSummaryRow[];
  processRows: MaterialSummaryRow[];
  hardwareTotal: number;
  processingTotal: number;
  total: number;
}

export interface CabinetProjectMaterialSummary {
  unitSummaries: CabinetUnitMaterialSummary[];
  materialCaiTotals: MaterialCaiTotal[];
  hardwareRows: MaterialSummaryRow[];
  processRows: MaterialSummaryRow[];
  hardwareTotal: number;
  processingTotal: number;
  total: number;
}

function round(n: number, decimals: number): number {
  const factor = Math.pow(10, decimals);
  return Math.round(n * factor) / factor;
}

function sizeLabel(widthCm: number, heightCm: number): string {
  return `${round(widthCm, 1)} x ${round(heightCm, 1)} cm`;
}

function materialName(ref: MaterialRef | null): string {
  return ref?.materialName ?? "未選材料";
}

function panelCategory(row: PanelResult): string {
  if (row.id.includes("drawer")) return "抽屜板材";
  if (row.name.includes("背板")) return "背板";
  if (row.isAutoGenerated) return "桶身板材";
  return "內部構件";
}

function caiLabel(actualCai: number, billableCai?: number): string {
  const actual = `${round(actualCai, 2)}才`;
  if (billableCai !== undefined && billableCai > actualCai) {
    return `${actual} / 計${round(billableCai, 2)}才`;
  }
  return actual;
}

function panelProcessCost(row: PanelResult): number {
  return (row.processes ?? []).reduce((sum, process) => sum + (process.includedInSubtotal ? process.cost : 0), 0);
}

function panelMaterialSubtotal(row: PanelResult): number {
  return Math.max(0, row.subtotal - row.addonsCost);
}

function doorMaterialSubtotal(row: DoorResult): number {
  return Math.max(0, row.subtotal - row.addonsCost);
}

function isProcessingHardware(row: HardwareResult): boolean {
  return row.id.includes("-profile-handle") || row.name.includes("加工");
}

function panelMaterialRow(row: PanelResult): MaterialSummaryRow {
  return {
    id: row.id,
    category: panelCategory(row),
    materialId: row.materialRef?.materialId ?? null,
    material: materialName(row.materialRef),
    itemName: row.name,
    quantity: row.quantity,
    size: sizeLabel(row.widthCm, row.heightCm),
    cai: row.billableTotalArea.cai,
    caiLabel: caiLabel(row.totalArea.cai, row.billableTotalArea.cai),
    note: "-",
    unitPrice: row.materialRef ? row.unitCost : null,
    subtotal: panelMaterialSubtotal(row),
    kind: "material",
  };
}

function processSummaryRow(params: {
  id: string;
  itemName: string;
  quantity: number | null;
  note: string;
  unitPrice: number | null;
  subtotal: number | null;
  category?: string;
}): MaterialSummaryRow {
  return {
    id: params.id,
    category: params.category ?? "加工",
    materialId: null,
    material: "後加工",
    itemName: params.itemName,
    quantity: params.quantity,
    size: "-",
    cai: null,
    caiLabel: "-",
    note: params.note,
    unitPrice: params.unitPrice,
    subtotal: params.subtotal,
    kind: "process",
  };
}

function panelProcessRow(parent: PanelResult, process: PanelProcessResult): MaterialSummaryRow {
  const parentQuantity = parent.quantity || 1;
  const quantity = process.quantity > 1 ? process.quantity : parentQuantity;
  const subtotal = round(process.unitCost * quantity, UNIT_CONFIG.COST_DECIMAL_PLACES);
  return processSummaryRow({
    id: `${parent.id}:${process.id}`,
    itemName: process.label.startsWith("加工-") ? process.label : `加工-${process.label}`,
    quantity,
    note: process.label,
    unitPrice: process.unitCost,
    subtotal,
  });
}

function panelRows(row: PanelResult): MaterialSummaryRow[] {
  const processes = row.processes ?? [];
  const rows = [panelMaterialRow(row), ...processes.map((process) => panelProcessRow(row, process))];
  const knownIncludedProcessCost = panelProcessCost(row);
  const remainingAddonCost = round((row.addonsCost ?? 0) - knownIncludedProcessCost, UNIT_CONFIG.COST_DECIMAL_PLACES);
  if (remainingAddonCost > 0) {
    rows.push(processSummaryRow({
      id: `${row.id}:panel-addon`,
      itemName: "板件加工",
      quantity: row.quantity,
      note: row.note ?? "板件加工",
      unitPrice: round(remainingAddonCost / Math.max(row.quantity, 1), UNIT_CONFIG.COST_DECIMAL_PLACES),
      subtotal: remainingAddonCost,
    }));
  }
  if (row.note && processes.length === 0 && remainingAddonCost <= 0) {
    rows.push(processSummaryRow({
      id: `${row.id}:note`,
      itemName: `加工-${row.note}`,
      quantity: row.quantity,
      note: row.note,
      unitPrice: null,
      subtotal: null,
    }));
  }
  return rows;
}

function doorMaterialRow(row: DoorResult): MaterialSummaryRow {
  return {
    id: row.id,
    category: "門片",
    materialId: row.materialRef?.materialId ?? null,
    material: materialName(row.materialRef),
    itemName: row.name,
    quantity: row.quantity,
    size: sizeLabel(row.widthCm, row.heightCm),
    cai: row.billableTotalArea.cai,
    caiLabel: caiLabel(row.totalArea.cai, row.billableTotalArea.cai),
    note: "-",
    unitPrice: row.materialRef?.pricePerUnit ?? null,
    subtotal: doorMaterialSubtotal(row),
    kind: "material",
  };
}

function doorAddonRows(row: DoorResult, input: DoorInput | undefined): MaterialSummaryRow[] {
  if (row.addonsCost <= 0) return [];
  if (!input || !row.materialRef || row.materialRef.unit !== "才") {
    return [processSummaryRow({
      id: `${row.id}:door-addon`,
      itemName: "門片加工",
      quantity: row.quantity,
      note: "門片加工",
      unitPrice: null,
      subtotal: row.addonsCost,
    })];
  }

  const addons = {
    ...DEFAULT_DOOR_ADDONS,
    ...input.addons,
    profileHandle: {
      ...DEFAULT_DOOR_ADDONS.profileHandle,
      ...input.addons?.profileHandle,
    },
  };
  const rows: MaterialSummaryRow[] = [];
  const cai = row.billableTotalArea.cai;

  if (addons.patternMatch === "grain") {
    const unitPrice = row.materialRef.pricePerUnit * (ADDON_PRICES.PATTERN_MATCH_GRAIN - 1);
    rows.push(processSummaryRow({
      id: `${row.id}:pattern`,
      itemName: "門片對花",
      quantity: cai,
      note: "門片對花",
      unitPrice,
      subtotal: round(cai * unitPrice, UNIT_CONFIG.COST_DECIMAL_PLACES),
    }));
  }

  if (addons.temperedGlass) {
    rows.push(processSummaryRow({
      id: `${row.id}:glass`,
      itemName: "強化玻璃",
      quantity: cai,
      note: "強化玻璃",
      unitPrice: ADDON_PRICES.TEMPERED_GLASS,
      subtotal: round(cai * ADDON_PRICES.TEMPERED_GLASS, UNIT_CONFIG.COST_DECIMAL_PLACES),
    }));
  }

  if (input.type === "HINGED" && addons.hingeHoleDrilling) {
    const hingesPerDoor = Math.max(
      UNIT_CONFIG.MIN_HINGES_PER_DOOR,
      Math.ceil(input.heightCm / UNIT_CONFIG.HINGE_SPACING_CM),
    );
    const quantity = hingesPerDoor * row.quantity;
    rows.push(processSummaryRow({
      id: `${row.id}:hinge-hole`,
      itemName: "門板鉸鏈孔",
      quantity,
      note: "門板鉸鏈孔",
      unitPrice: ADDON_PRICES.HINGE_HOLE_DRILLING,
      subtotal: quantity * ADDON_PRICES.HINGE_HOLE_DRILLING,
    }));
  }

  return rows;
}

function hardwareSummaryRow(row: HardwareResult): MaterialSummaryRow {
  const isProcess = isProcessingHardware(row);
  return {
    id: row.id,
    category: isProcess ? "加工" : "五金 / 另料",
    materialId: row.materialRef?.materialId ?? null,
    material: row.materialRef?.materialName ?? "-",
    itemName: row.name,
    quantity: row.quantity,
    size: "-",
    cai: null,
    caiLabel: "-",
    note: row.description || "-",
    unitPrice: row.unitCost > 0 ? row.unitCost : null,
    subtotal: row.subtotal,
    kind: isProcess ? "process" : "hardware",
  };
}

function accessoryRow(row: AccessoryResult): MaterialSummaryRow {
  return {
    id: row.id,
    category: "配件",
    materialId: row.materialRef?.materialId ?? null,
    material: materialName(row.materialRef),
    itemName: row.name,
    quantity: row.quantity,
    size: sizeLabel(row.widthCm, row.heightCm),
    cai: row.totalArea.cai,
    caiLabel: `${round(row.totalArea.cai, 2)}才`,
    note: "-",
    unitPrice: row.materialRef?.pricePerUnit ?? null,
    subtotal: row.subtotal,
    kind: "accessory",
  };
}

function mergeMaterialCaiTotals(rows: MaterialSummaryRow[]): MaterialCaiTotal[] {
  const map = new Map<string, MaterialCaiTotal>();
  for (const row of rows) {
    if ((row.kind !== "material" && row.kind !== "accessory") || !row.materialId || row.cai === null) continue;
    const existing = map.get(row.materialId);
    if (existing) {
      existing.cai = round(existing.cai + row.cai, UNIT_CONFIG.AREA_DECIMAL_PLACES);
      continue;
    }
    map.set(row.materialId, {
      materialId: row.materialId,
      materialName: row.material,
      cai: row.cai,
    });
  }
  return Array.from(map.values());
}

function mergeHardwareRows(rows: MaterialSummaryRow[]): MaterialSummaryRow[] {
  const map = new Map<string, MaterialSummaryRow>();
  for (const row of rows) {
    const key = [row.itemName, row.material, row.note, row.unitPrice].join("|");
    const existing = map.get(key);
    if (!existing) {
      map.set(key, { ...row, id: `summary:${key}` });
      continue;
    }
    existing.quantity = (existing.quantity ?? 0) + (row.quantity ?? 0);
    existing.subtotal = (existing.subtotal ?? 0) + (row.subtotal ?? 0);
  }
  return Array.from(map.values());
}

export function buildCabinetUnitMaterialSummary(
  result: CabinetUnitResult,
  input?: CabinetUnitInput,
): CabinetUnitMaterialSummary {
  const rows: MaterialSummaryRow[] = [
    ...result.panels.flatMap(panelRows),
    ...result.internalParts.flatMap(panelRows),
  ];

  const hardwareByDoorId = new Map<string, MaterialSummaryRow[]>();
  const hardwareRows: MaterialSummaryRow[] = [];
  const looseProcessRows: MaterialSummaryRow[] = [];

  for (const hardware of result.hardware) {
    const row = hardwareSummaryRow(hardware);
    const doorId = result.doors.find((door) => hardware.id.startsWith(`${door.id}-`))?.id;
    if (row.kind === "process" && doorId) {
      const existing = hardwareByDoorId.get(doorId) ?? [];
      existing.push(row);
      hardwareByDoorId.set(doorId, existing);
      continue;
    }
    if (row.kind === "process") {
      looseProcessRows.push(row);
      continue;
    }
    hardwareRows.push(row);
  }

  for (const door of result.doors) {
    rows.push(doorMaterialRow(door));
    const doorInput = input?.doors.find((item) => item.id === door.id);
    rows.push(...doorAddonRows(door, doorInput));
    rows.push(...(hardwareByDoorId.get(door.id) ?? []));
  }

  rows.push(...looseProcessRows);
  rows.push(...hardwareRows);
  rows.push(...result.accessories.map(accessoryRow));

  const processRows = rows.filter((row) => row.kind === "process");

  return {
    unitId: result.unitId,
    unitName: result.unitName,
    rows,
    materialCaiTotals: mergeMaterialCaiTotals(rows),
    hardwareRows,
    processRows,
    hardwareTotal: hardwareRows.reduce((sum, row) => sum + (row.subtotal ?? 0), 0),
    processingTotal: processRows.reduce((sum, row) => sum + (row.subtotal ?? 0), 0),
    total: result.summary.totalCost,
  };
}

export function buildCabinetProjectMaterialSummary(
  result: CabinetProjectResult,
  inputs: CabinetUnitInput[] = [],
): CabinetProjectMaterialSummary {
  const unitSummaries = result.unitResults.map((unitResult) => (
    buildCabinetUnitMaterialSummary(unitResult, inputs.find((input) => input.id === unitResult.unitId))
  ));
  const allRows = unitSummaries.flatMap((summary) => summary.rows);
  const allHardwareRows = unitSummaries.flatMap((summary) => summary.hardwareRows);
  const allProcessRows = unitSummaries.flatMap((summary) => summary.processRows);

  return {
    unitSummaries,
    materialCaiTotals: mergeMaterialCaiTotals(allRows),
    hardwareRows: mergeHardwareRows(allHardwareRows),
    processRows: allProcessRows,
    hardwareTotal: allHardwareRows.reduce((sum, row) => sum + (row.subtotal ?? 0), 0),
    processingTotal: allProcessRows.reduce((sum, row) => sum + (row.subtotal ?? 0), 0),
    total: result.projectTotal,
  };
}
